spring:
  application:
    name: school-web-management

  #配置数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/school-management
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

#配置MyBatis的日志输出
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名法
    map-underscore-to-camel-case: true

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug